---
delay: 1                                       # Wait time between AO3 requests in seconds
files:
  output: 'data/work_id_list.txt'
params:
  utf8: '✓'                                    # Don't alter
  commit: 'Sort and Filter'                    # Don't alter 
  work_search[sort_column]: 'created_at'       # or 'date_posted'
  work_search[other_tag_names]: '' 
  work_search[excluded_tag_names]: ''
  work_search[crossover]: ''
  work_search[complete]: ''
  work_search[words_from]: ''
  work_search[words_to]: ''
  work_search[date_from]: ''
  work_search[date_to]: ''
  work_search[query]: ''
  work_search[language_id]: ''
  tag_id: 'The Mandalorian (TV)'
  page: ''                                     # Don't alter
type_of: 'works'
#test_id: 11030034
test_id: 8543680
