version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/python:3.7.3'

    working_directory: ~/repo

    steps:
      - checkout

      #- restore_cache:
      #   keys:
      #     - v1-dependencies-{{ checksum 'requirements.txt'}}
      #     - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      #- save_cache:
      #   paths:
      #     - ./.venv
      #   key: v1-dependencies-{{ checksum 'requirements.txt'}}

      - run:
          name: run linter
          command: |
            python3 -m venv venv
            . venv/bin/activate
            flake8

      #- run:
      #   name: run tests
      #   command: |
      #     . .venv/bin/activate
      #     python manage.py test

      #- store_artifacts:
      #   path: test-reports
      #   destination: test-reports

